columns_to_use: ['target', 'TaxaDeUtilizacaoDeLinhasNaoGarantidas', 'Idade',
                 'NumeroDeVezes30-59DiasAtrasoNaoPior', 'TaxaDeEndividamento',
                 'RendaMensal', 'NumeroDeLinhasDeCreditoEEmprestimosAbertos',
                 'NumeroDeVezes90DiasAtraso', 'NumeroDeEmprestimosOuLinhasImobiliarias',
                 'NumeroDeVezes60-89DiasAtrasoNaoPior', 'NumeroDeDependentes']

variables_imputer: ['RendaMensal','NumeroDeDependentes']


variables_discretiser: ['TaxaDeUtilizacaoDeLinhasNaoGarantidas','TaxaDeEndividamento','RendaMensal']

train_dataset_name: 'train.csv' 


test_dataset_name: 'test.csv'

random_state: 42

target_variable: 'target'

test_size: 0.33

model_name: 'Logistic_Regression'

stratified_k_folder_n_splits: 5

cross_val_scoring_metric: 'roc_auc'


# MLFlow parameters

experiment_name: 'prob_loan_exp'


# MLFlow MetricThreshold() parameters

metric_to_evaluate: 'precision_score' # accuracy_score, recall_score, f1_score, roc_auc, precision_recall_auc

metric_threshold: 0.1

metric_min_absolute_change: 0.05

metric_min_relative_change: 0.05

greater_is_better: True


# MLFlow mlflow.evaluate() parameters

model_type: 'classifier'


# Hyperopt parameters

max_evals: 100
