columns_to_use: ['target', 'TaxaDeUtilizacaoDeLinhasNaoGarantidas', 'Idade',
                 'NumeroDeVezes30-59DiasAtrasoNaoPior', 'TaxaDeEndividamento',
                 'RendaMensal', 'NumeroDeLinhasDeCreditoEEmprestimosAbertos',
                 'NumeroDeVezes90DiasAtraso', 'NumeroDeEmprestimosOuLinhasImobiliarias',
                 'NumeroDeVezes60-89DiasAtrasoNaoPior', 'NumeroDeDependentes']

variables_imputer: ['RendaMensal','NumeroDeDependentes']


variables_discretiser: ['TaxaDeUtilizacaoDeLinhasNaoGarantidas','TaxaDeEndividamento','RendaMensal']

train_dataset_name: 'train.csv' 


test_dataset_name: 'test.csv'

random_state: 42

target_variable: 'target'

test_size: 0.33

model_name: 'Logistic_Regression'